### ISSUE TITLE
Fix error with apiKey in version 4.6.1 

### ISSUE THREAD

**Issue by schurakov** [Visual-Regression-Tracker/agent-playwright#51]
I set the config from the code. In the version 4.6.1 get an error :

`Error: apiKey is not specified
      at Object.validateConfig (node_modules/@visual-regression-tracker/sdk-js/dist/helpers/config.helper.js:55:15)
      at new VisualRegressionTracker (node_modules/@visual-regression-tracker/sdk-js/dist/visualRegressionTracker.js:35:19)
      at new PlaywrightVisualRegressionTracker (node_modules/@visual-regression-tracker/agent-playwright/dist/playwrightVisualRegressionTracker.js:16:20)`

In the version 4.5.0 this config works.

**Comment by pashidlos** [comment]
cannot reproduce 
please, provide code example

**Comment by pashidlos** [comment]
the issue was in wrong param order in `PlaywrightVisualRegressionTracker` ctor
before `4.6.1` it was `new PlaywrightVisualRegressionTracker(config, browserType)` 
after update they were swapped and should be `new PlaywrightVisualRegressionTracker(browserType, config)`
example project contained the issue and was fixed as well

**Comment by schurakov** [comment]
I used the wrong order of the arguments in the constructor, sorry

**Comment by pashidlos** [comment]
@schurakov my bad, issue was in example project
param order in `PlaywrightVisualRegressionTracker` ctor changed
before `4.6.1` it was `new PlaywrightVisualRegressionTracker(config, browserType)` 
after update they were swapped and should be `new PlaywrightVisualRegressionTracker(browserType, config)`

thanks for pointing it out!
